type = "publication"
title = "Publications"
description = "Conference presentations and manuscripts."

[[items]]
title = "The Neural Correlates of Auditory and Visual Statistical Learning and the Underlying Modality Specificity"
venue = "ICPEAL 2025"
date = "2025-12-01"
type = "Poster Presentation"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "Neuro-behavioral Correlates of Statistical Learning in English Second Language Comprehension: The Specificity of Statistical Learning Modality"
venue = "SNL 2025"
date = "2025-09-01"
type = "Poster Presentation"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "Neuro-behavioral Correlates of Visual Statistical Learning in Chinese Second Language Reading"
venue = "SNL 2024"
date = "2024-10-01"
type = "Poster Presentation"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "The Specificity of Contextual Effects in the Processing of Internet Ambiguous Words"
venue = "IACL-30"
date = "2024-05-01"
type = "Oral Presentation"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "Neuro-behavioral Correlates of Statistical Learning in English Second Language Comprehension"
venue = "7th International Conference of Psycholinguistics in China"
date = "2024-05-01"
type = "Oral Presentation"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "Field Dependence-independence Modulates the Performance in Different Types of Visual Statistical Learning"
venue = "Manuscript under review"
date = "2023-01-01"
type = "Manuscript"
authors = ["Bao, B."]
selected = false
links = []
