type = "publication"
title = "会议报告与论文"
description = "我的学术会议报告与研究成果。"

[[items]]
title = "The Neural Correlates of Auditory and Visual Statistical Learning and the Underlying Modality Specificity"
venue = "ICPEAL 2025（第19届东亚语言加工国际会议）"
date = "2025-12-01"
type = "墙报展示"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "Neuro-behavioral Correlates of Statistical Learning in English Second Language Comprehension: The Specificity of Statistical Learning Modality"
venue = "SNL 2025（语言神经生物学会第17届年会）"
date = "2025-09-01"
type = "墙报展示"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "Neuro-behavioral Correlates of Visual Statistical Learning in Chinese Second Language Reading"
venue = "SNL 2024（语言神经生物学会第16届年会）"
date = "2024-10-01"
type = "墙报展示"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "The Specificity of Contextual Effects in the Processing of Internet Ambiguous Words"
venue = "IACL-30（国际中国语言学学会第30届年会）"
date = "2024-05-01"
type = "口头报告"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "Neuro-behavioral Correlates of Statistical Learning in English Second Language Comprehension"
venue = "第七届中国心理语言学国际研讨会"
date = "2024-05-01"
type = "口头报告"
authors = ["Bao, B."]
selected = true
links = []

[[items]]
title = "Field Dependence-independence Modulates the Performance in Different Types of Visual Statistical Learning"
venue = "投稿中"
date = "2023-01-01"
type = "论文手稿"
authors = ["Bao, B."]
selected = false
links = []
